name: places
description: Interesting places guide application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_svg: ^0.21.0+1

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto/Roboto-Regular.ttf
        - asset: res/fonts/Roboto/Roboto-Medium.ttf
          weight: 600
        - asset: res/fonts/Roboto/Roboto-Bold.ttf
          weight: 700

  assets:
    - res/images/sights/

  
